apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:T746NhSVgB88bfzOVeyTzPGtOKtOyIqIh/MHLD0HhEnrkMjl//2H9wUPM5xt3rKnUc8+U5DjPkouRzun4mKghTIOM47LqqOGNQ1R1b87TPGgBH/F/9NP1oL5kqD9S6whhJEUfq0KBdrrvB5/VOGx4hkoEFDuj/i4MVU50KCxhKfPsw==,iv:9Ke949BmqtTNfSCT1nRQbJs97QseXBR1DeDDZN5j+pg=,tag:5nzE0IvXuuh8WhwdcshyOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-15T19:07:26Z"
    mac: ENC[AES256_GCM,data:fpYT3zVg9xdnBfyz5tE2tdBhkVFkt0d9D/yoYg6LT1cWcd+sZxuTZMYKMcqVaD0rXhKnFxi2TNq9JJNB/Psxj8hO3nq0DDQQ5e26y9W4mWltMXgj3sembK25N1ci8u00q8t2DpQ+wHOps5PKEl+HjZkB7VOASy7cWSRjHf5MbZo=,iv:WKWyQK2m5Tii7133t7Zg0m0R94AmiXlSI8D39FKHgXQ=,tag:rsOrZdDLyhjKk6+iV720Ew==,type:str]
    pgp:
        - created_at: "2021-07-15T18:56:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7XuupO03uxSAQ/8CWwlHwye53Tj3m4bfOwTAplfRtDxosd986fjw8u/PCh7
            oWxIQq7ZYAF8C0lK0hb+fsl/X/VCVDVFJRBdqbRfVJSpZ93xzMM5zmgnLyHaTc1x
            WNcNueHb/gfnWzfhiVAeg7weVK07IFpxY4gZ87aCx3FWICWs0UDENCI6kkm7tmCo
            r0Ge3AFyUcJc2mLIo3zj55Dq0tdGxqu1hiZa7eFLkh6F47sKSYS7snNNwCP9omPX
            kJCZo6vDcsZ1W0lJDoyDk9RKWRB/la2vwKkfpHweJ1Q/XsvpiWnJIkz5Wf4dBRpJ
            NwRwMKwmNOxkxjMfvfCMcEdrtfklXVXaDRmlMmpWsQFUlr/KBDWZncgbITnKrRV3
            Torx+r0BRrbUhq2oufegb6nIvbRajsojPLCy5mSq41w4R2WmFeruXaQnAgbrCEo4
            SVgTvQs+i9YcB3AST7erwT6Pr4clcpxRbROI33WqJERfbj1Up11Wqd9ZOC/gr9Yy
            PpBQDT3EtHzDOR4zxqF8Y0kFs7aDRnDmQnvQScDfm4Bb3aZ0b1A6UcljXhLEyo3D
            0148ISbux3f5HCiq4jX17qt2AoPgNkQaSlmCi0/ccP4UcT4v2OqqRn11vAqF24rv
            aWIyC/g/5J4Md501tN6SMwBiVsTGb/5sgnBbcKSrZPEKErVaTsumMefC10ifRWzS
            XgGvUwCVOXzc9kL9FCNT9AD3M2cvjQJwn8n4uVbatocqm7CJKL94bvBRxZ+ADQBZ
            zDjmbwsFUJhxDcW+rYpAFR8x2zwYAvaVR8rBry4SH+8ybcT20qhxp5Wg9h+gKJ8=
            =2mfi
            -----END PGP MESSAGE-----
          fp: 426F41161DE3CE8CD962A3DB25F5E012E868DE08
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
